/*
  No relative dates or ISO8601
*/
// // This file was generated by lezer-generator. You probably shouldn't edit it.
// import {LRParser} from "@lezer/lr"
// export const parser = LRParser.deserialize({
//   version: 13,
//   states: "!jQYQPOOO_QPO'#C`OgQPO'#C_OOQO'#Cd'#CdQYQPOOOlQPO,58zOqQQO,58yOOQO-E6b-E6bOOQO1G.f1G.fOvQPO'#CbOOQO1G.e1G.eOOQO,58|,58|",
//   stateData: "}~OZOSPOS~OTPO~O[TO]SX~O]UO~OTWO~OVXO~O^ZO~OV~",
//   goto: "kXPPPY^PbPeTROSTQOSRYUQSORVS",
//   nodeNames: "⚠ Comment Cascade Event DateRange Date EventDescription Text",
//   maxTerm: 14,
//   skippedNodes: [0,1],
//   repeatNodeCount: 1,
//   tokenData: "'g~R`OX!TXY!`YZ#bZ]!T]^!`^p!Tpq!`q}!T}!O#u!O!P!T!P!Q$S!Q![$r![!]&w!]#h!T#h#i'U#i~!TQ!YQVQOY!TZ~!T~!gWZ~VQOX!TXY!`YZ#PZ]!T]^!`^p!Tpq!`q~!T~#USZ~XY#PYZ#P]^#Ppq#P~#iS^~Z~XY#PYZ#P]^#Ppq#PR#|Q[PVQOY!TZ~!T~$XSVQOY!TZ!P!T!P!Q$e!Q~!T~$lQP~VQOY$eZ~$eR$yTTPVQOY!TZ!P!T!P!Q%Y!Q![$r![~!TR%_SVQOY!TZ!Q!T!Q![%k![~!TR%rTTPVQOY!TZ!P!T!P!Q&R!Q![%k![~!TR&WSVQOY!TZ!Q!T!Q![&d![~!TR&kSTPVQOY!TZ!Q!T!Q![&d![~!TR'OQ]PVQOY!TZ~!TR'ZSVQOY!TZ#c!T#c#d#u#d~!T",
//   tokenizers: [0, 1],
//   topRules: {"Cascade":[0,2]},
//   tokenPrec: 43
// })

// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "%|QYQPOOOeQPO'#CbOsQQO'#CdOOQO'#Cj'#CjOxQPO'#CaOOQO'#Ca'#CaO!TQPO'#C`O!]QSO'#C_OOQO'#Ci'#CiQYQPOOO!bQPO,58|OOQO,59P,59PO!gQPO,59OO!lQPO'#CeOOQO-E6h-E6hOOQO,58z,58zOYQPO,58zO!qQPO'#CgOOQO,58y,58yOOQO-E6g-E6gO!vQPO1G.hO#RQQO1G.jO#WQPO1G.fOOQO,59R,59RO#]QPO7+$SO#bQPO7+$UOOQO7+$Q7+$QOOQO<<Gn<<GnO#gQPO<<GpO#lQPOAN=[O#qQPOG22vO#vQPOLD(bO#{QPO!$'K|O$QQQO!)9AhO$VQPO!.K7SOOQO!4/,n!4/,nO$_QPO!4/,nOOQO!9A!Y!9A!Y",
  stateData: "$i~OaOSPOS~OVPOeQOkTO~OYZOcYObUXlUX~Of[O~OV]ObTXlTX~Ob_Ol`O~O[aO~OVdO~OgeO~OYZO~OmgO~OchObUilUi~OfiO~ObjO~OVkO~OglO~OhmO~OgnO~OboO~OgpO~ObqO~OirO~OdsOjtO~OduO~OVge[~",
  goto: "!]_PPP`dhoPotPzP}!TTWOXTVOXSUOXRf`VTOX`XROSX`RbVQXORcXUSOX`R^S",
  nodeNames: "⚠ Comment Cascade Event DateRange Date SlashDate Digits ISO8601 RelativeDate MeasureWord EventDescription Text",
  maxTerm: 29,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "8f~RpOX#VXY#bYZ$dZ]#V]^#b^p#Vpq#bq}#V}!O$w!O!P%W!P!Q%e!Q![&V![!](f!]!v#V!v!w(s!w!|#V!|!})Q!}#W#V#W#X)_#X#[#V#[#]*u#]#a#V#a#b+|#b#c2u#c#g#V#g#h3v#h#i5y#i#k#V#k#l6i#l#m#V#m#n7p#n~#VS#[Q[SOY#VZ~#V~#iWa~[SOX#VXY#bYZ$RZ]#V]^#b^p#Vpq#bq~#V~$WSa~XY$RYZ$R]^$Rpq$R~$kSm~a~XY$RYZ$R]^$Rpq$RV%QQfQlP[SOY#VZ~#VT%_QjP[SOY#VZ~#V~%lSc~[SOY#VZ!P#V!P!Q%x!Q~#V~&PQP~[SOY%xZ~%xV&^SVP[SOY#VZ!Q#V!Q![&j![~#VV&uSiQVPgP[SOY#VZ!Q#V!Q!['R![~#VV'[SiQVP[SOY#VZ!Q#V!Q!['h![~#VV'sSiQVPeP[SOY#VZ!Q#V!Q![(P![~#VV(YSiQVP[SOY#VZ!Q#V!Q![(P![~#VT(mQbP[SOY#VZ~#VT(zQhP[SOY#VZ~#VT)XQdP[SOY#VZ~#VT)fSYP[SOY#VZ#T#V#T#U)r#U~#VT)wS[SOY#VZ#m#V#m#n*T#n~#VT*[SYP[SOY#VZ#g#V#g#h*h#h~#VT*oQYP[SOY#VZ~#VT*|SYP[SOY#VZ#c#V#c#d+Y#d~#VT+_S[SOY#VZ#i#V#i#j+k#j~#VT+pS[SOY#VZ#f#V#f#g*T#g~#VT,RW[SOY#VZ#]#V#]#^,k#^#c#V#c#d1p#d#g#V#g#h*h#h~#VT,pU[SOY#VZ#`#V#`#a-S#a#b#V#b#c0c#c~#VT-XS[SOY#VZ#`#V#`#a-e#a~#VT-jS[SOY#VZ#]#V#]#^-v#^~#VT-{S[SOY#VZ#g#V#g#h.X#h~#VT.^S[SOY#VZ#X#V#X#Y.j#Y~#VT.oS[SOY#VZ#V#V#V#W.{#W~#VT/QS[SOY#VZ#c#V#c#d/^#d~#VT/cS[SOY#VZ#b#V#b#c/o#c~#VT/tS[SOY#VZ#W#V#W#X0Q#X~#VT0VS[SOY#VZ#g#V#g#h*h#h~#VT0jUYP[SOY#VZ#g#V#g#h*h#h#i#V#i#j0|#j~#VT1RS[SOY#VZ#h#V#h#i1_#i~#VT1dS[SOY#VZ#X#V#X#Y*T#Y~#VT1uS[SOY#VZ#b#V#b#c2R#c~#VT2WS[SOY#VZ#h#V#h#i2d#i~#VT2iS[SOY#VZ#[#V#[#]*T#]~#VT2zS[SOY#VZ#c#V#c#d3W#d~#VT3]S[SOY#VZ#k#V#k#l3i#l~#VT3pQkP[SOY#VZ~#VT3}SYP[SOY#VZ#X#V#X#Y4Z#Y~#VT4`S[SOY#VZ#V#V#V#W4l#W~#VT4sUYP[SOY#VZ#c#V#c#d5V#d#g#V#g#h*h#h~#VT5[S[SOY#VZ#b#V#b#c5h#c~#VT5mS[SOY#VZ#W#V#W#X*T#X~#VT6OS[SOY#VZ#c#V#c#d6[#d~#VT6cQlP[SOY#VZ~#VT6pSYP[SOY#VZ#X#V#X#Y6|#Y~#VT7RS[SOY#VZ#X#V#X#Y7_#Y~#VT7dS[SOY#VZ#_#V#_#`*T#`~#VT7wSYP[SOY#VZ#X#V#X#Y8T#Y~#VT8YS[SOY#VZ#T#V#T#U+k#U~#V",
  tokenizers: [0, 1, 2],
  topRules: {"Cascade":[0,2]},
  tokenPrec: 158
})
