// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 13,
  states:
    "!jQVQPOOO[QPO'#C_OdQPO'#C^OOQO'#Cc'#CcQVQPOOOiQPO,58yOnQQO,58xOOQO-E6a-E6aOOQO1G.e1G.eOsQPO'#CaOOQO1G.d1G.dOOQO,58{,58{",
  stateData: "z~OYOS~OSPO~OZTO[RX~O[UO~OSWO~OUXO~O]ZO~OU~",
  goto: "jWPPX]PaPdTROSTQOSRYUQSORVS",
  nodeNames: "⚠ Cascade Event DateRange Date EventDescription Text",
  maxTerm: 13,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData:
    "&t~R_OX!QXY!]YZ#_Z]!Q]^!]^p!Qpq!]q}!Q}!O#r!O!Q!Q!Q![$P![!]&U!]#h!Q#h#i&c#i~!QQ!VQUQOY!QZ~!Q~!dWY~UQOX!QXY!]YZ!|Z]!Q]^!]^p!Qpq!]q~!Q~#RSY~XY!|YZ!|]^!|pq!|~#fS]~Y~XY!|YZ!|]^!|pq!|R#yQZPUQOY!QZ~!QR$WTSPUQOY!QZ!P!Q!P!Q$g!Q![$P![~!QR$lSUQOY!QZ!Q!Q!Q![$x![~!QR%PTSPUQOY!QZ!P!Q!P!Q%`!Q![$x![~!QR%eSUQOY!QZ!Q!Q!Q![%q![~!QR%xSSPUQOY!QZ!Q!Q!Q![%q![~!QR&]Q[PUQOY!QZ~!QR&hSUQOY!QZ#c!Q#c#d#r#d~!Q",
  tokenizers: [0, 1],
  topRules: { Cascade: [0, 1] },
  tokenPrec: 40,
});
