// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "nOQOPOOOOOO'#C^'#C^OOOO'#Ca'#CaQQOPOOOOOO-E6_-E6_",
  stateData: "Y~ORPOSPO~O",
  goto: "aUPPVPPZTQORQRORSR",
  nodeNames: "⚠ Cascade Entry TagColor Event",
  maxTerm: 6,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&g~RSXY_pq_st#}!Q![k~bRXY_pq_!Q![k~nS}!Oz!P!Q#U!Q![k![!]#P~}P!Q![!Q~!TR!P!Q!^!Q![!Q![!]#P~!aP!Q![!d~!gR!P!Q!p!Q![!d![!]#P~!sP!Q![!v~!yQ!Q![!v![!]#P~#UOS~~#XP!Q![#[~#_S}!Oz!P!Q#k!Q![#[![!]#P~#nP!Q![#q~#tR}!Oz!Q![#q![!]#P~$QR!Q![$Z!c!}$Z#T#o$Z~$^S!Q![$Z![!]$j!c!}$Z#T#o$Z~$mYX^%]pq%]#y#z%]$f$g%]#BY#BZ%]$IS$I_%]$I|$JO%]$JT$JU%]$KV$KW%]&FU&FV%]~%`]X^%]pq%]!Q![&X!c!}&X#T#o&X#y#z%]$f$g%]#BY#BZ%]$IS$I_%]$I|$JO%]$JT$JU%]$KV$KW%]&FU&FV%]~&^RR~!Q![&X!c!}&X#T#o&X",
  tokenizers: [0],
  topRules: {"Cascade":[0,1]},
  tokenPrec: 0
})
